name: Tests

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Setup Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: make test
